plugins/platforms/github/mod.test.ts, plugins/platforms/github/mod.ts, src/cli/commands/default.ts, src/platform/plugin.ts, src/plugin/mod.ts
Add a header with the version used when the files were generated.
An user can compare the latest available version with the version in the CI files to decide if they need to update.
=> Include a header in generated  files

plugins/stack/html/formatters.ts, plugins/stack/html/linters.ts, plugins/stack/html/mod.test.ts, plugins/stack/html/mod.ts, plugins/stack/mod.ts, templates/github/html/format.yml, templates/github/html/lint.yml
Adds prettier as a formatter for .html and Vue files.
Uses ESLint and Stylelint for Vue linting, choosing ESLint as a default.
To test:
- Check if the unit test is passing `deno --unstable test --allow-read plugins/stack/html/`;
- Try to generate the Pipelinit files on a project with vue and hrml files.
Resolves: https://github.com/pipelinit/pipelinit-cli/issues/7
=> Add html stack

.github/workflows/pipelinit.javascript.format.yaml, .github/workflows/pipelinit.javascript.lint.yaml, .github/workflows/pipelinit.javascript.test.yaml, README.md, core/plugins/stack/docker/mod.test.ts, core/plugins/stack/docker/mod.ts, core/plugins/stack/java/mod.test.ts, core/plugins/stack/java/mod.ts, core/plugins/stack/javascript/mod.test.ts, core/plugins/stack/mod.ts, core/plugins/stack/python/django.ts, core/plugins/stack/python/mod.test.ts, core/plugins/stack/python/mod.ts, core/templates/github/docker/build.yml, core/templates/github/docker/lint.yml, core/templates/github/java/build.yaml, core/templates/github/javascript/test.yaml, core/templates/github/python/lint.yaml, core/templates/github/python/test.yml
As described in the issue #23, using as example the GitHub starters CI, add to the Pipelinit the following stacks:
- Docker stack
- Lint stage
- Build stage
- Java stack
- Build stage with Gradle 
- Complement python stack
- Django and PyTest
- Black as formatter and flake8 adjusted
- Complement JavaScript stack
- Add a stage test
To test:
- Check if the unit tests pass 
- Try to generate the Pipelinit CI accordingly to each stack using the sample projects https://github.com/pipelinit/pipelinit-cli/tree/feat/github-starter-stacks#examples
=> Add docker stack and complement existing

core/plugins/stack/javascript/mod.test.ts, core/plugins/stack/javascript/mod.ts, core/plugins/stack/javascript/test.ts, core/templates/github/javascript/test.yaml
Checks if the project has a declared test command defined
To test:
- Check on repositories with the `test` command on the package.json if the `pipelinit.javascript.test.yaml` **is created**.  
- Check on repositories without the `test` command on the package.json if the `pipelinit.javascript.test.yaml` **is not created**.  
Projects tested:
Without test declared: https://github.com/pipelinit/pipelinit-sample-vue-html
With test declared: https://github.com/pipelinit/action
=> fix: Checks if the project has a declared test command defined

core/plugins/stack/html/frameworks.ts, core/plugins/stack/html/mod.test.ts, core/plugins/stack/html/mod.ts, core/plugins/stack/html/vue.ts, core/plugins/stack/python/frameworks.ts, core/plugins/stack/python/mod.test.ts, core/plugins/stack/python/mod.ts, core/templates/github/html/lint.yml, core/templates/github/python/test.yml
Adds a boolean identifier checking if the project is VUE
for the HTML introspection.
Resolves: https://github.com/pipelinit/pipelinit-cli/issues/36
To test:
- Check if the lint stage for HTML stack **IS NOT GENERATED** in this project https://github.com/renanstn/poll-generator or any project with html files and **no VUE files**
=> fix: adjust html stack vue identification

.github/workflows/release.yaml, cli/Dockerfile, cli/build.ts
Changes the behavior of `build.ts`and adds a new workflow for releasing binaries.
Check the commit messages for further details
=> New release automation

core/plugins/stack/mod.ts, core/plugins/stack/shell/linters.ts, core/plugins/stack/shell/mod.test.ts, core/plugins/stack/shell/mod.ts, core/plugins/stack/shell/shellcheck.ts, core/templates/github/shell/lint.yml
Adds a first implementation of the shell stack
using the ludeeus/action-shellcheck in the template
At first, it only checks .sh and .bash files
Resolves: https://github.com/pipelinit/pipelinit-cli/issues/9
To test:
- Run on a project with sh or bash files changed on a pull request
Example:
https://github.com/pipelinit/pipelinit-sample-python/pull/2/checks?check_run_id=3700192189
https://github.com/pipelinit/pipelinit-sample-python/pull/2/checks?check_run_id=3700097744
=> feat: add shell stack

core/plugins/stack/docker/mod.ts, core/templates/github/docker/build.yml, core/templates/github/docker/lint.yml
To improve the docker stack uses the git ls-files command, to exclude the git ignore and then loop through the project docker files using the lint and build command in each file.
Resolves: https://github.com/pipelinit/pipelinit-cli/issues/41
To test:
- Test on a project with multiples Dockerfiles
- Test if the pipeline triggers with changes in any Dockerfile
- Test if the lint and build stage runs for all Dockerfiles inside the project 
Example runs:
https://github.com/pipelinit/pipelinit-sample-docker/runs/3724322039?check_suite_focus=true
https://github.com/pipelinit/pipelinit-sample-docker/runs/3724293013?check_suite_focus=true
=> feat: add lint and build for multiple docker files

CONTRIBUTING.md, docs/tutorials/creating-a-plugin-for-markdown.md
With a concrete example on how to write a stack plugin to lint Markdown in the GitHub Actions workflow CI system.
=> docs: add a tutorial

docs/reference/stack-support.md
Update the detailed stack support with the tools used in the Docker, Java and Shell script stacks
=> docs: add Docker, Java and sh to stack support

core/plugins/stack/python/black.ts, core/plugins/stack/python/dependencies.ts, core/plugins/stack/python/flake8.ts, core/plugins/stack/python/formatters.ts, core/plugins/stack/python/frameworks.ts, core/plugins/stack/python/linters.ts, core/plugins/stack/python/mod.test.ts, core/plugins/stack/python/mod.ts, core/plugins/stack/python/packageManager.ts, core/plugins/stack/python/pytest.ts, core/templates/github/python/lint.yaml, core/templates/github/python/test.yml
Following the roadmap for the product with this PR we start expanding our python stack capabilities first adding the
following  package managers: 
- Pipenv
- Poetry 
- Requirements file
With this change now is possible to detect what dependency the project already has, thus making more easy to build an accurate template with the correct version of the lint and test dependencies and from this change was possible
to update the lint and format template that now verify if the project already has a linter configuration and installs it accordingly.
Resolves: https://github.com/pipelinit/pipelinit-cli/issues/53
Resolves: https://github.com/pipelinit/pipelinit-cli/issues/48
Resolves: https://github.com/pipelinit/pipelinit-cli/issues/50
To test:
- Run the unit test
- Test Pipelinit Lint and Format …
=> Improve python support

core/plugins/stack/python/formatters.ts, core/plugins/stack/python/isort.ts, core/plugins/stack/python/mod.test.ts, core/templates/github/python/lint.yaml
Adds a first implementation of the `isort` formatter
for the python stack and sets it in the default formatters along with `black`
Resolves: https://github.com/pipelinit/pipelinit-cli/issues/47
To test:
- Test in any python project
Example runs:
- With dependency: https://github.com/pipelinit/pipelinit-sample-python/pull/2/checks?check_run_id=3806362825
- As default recommendation: https://github.com/pipelinit/pipelinit-sample-python/runs/3806321040?check_suite_focus=true
=> Add support for isort

core/plugins/stack/python/dependencies.ts, core/plugins/stack/python/mod.test.ts, core/plugins/stack/python/packageManager.ts, core/templates/github/javascript/lint.yaml
The JavaScript lint template in some conditional added some unnecessary spaces that ended up broken the pipeline on GitHub.
Adjusted the python dependencies search to only see a package manager file in the project root path with that, we can avoid a situation where Pipelinit detects a dependency, but when running the pipeline  it can't install it, leaving the pipeline non-functional.
Resolves: https://github.com/pipelinit/pipelinit-cli/issues/88
To test:
- Test in any project with python package managers inside the dependencies and check if the generated files are cohesive. Ex: https://github.com/joao10lima/pipelinit-cli/pull/1
=> Fix javascript lint template and python dependencies search

cli/tests/default_test.ts, cli/tests/fixtures/ruby/rubocop-lint/expected/.github/workflows/pipelinit.ruby.lint.yaml, cli/tests/fixtures/ruby/rubocop-lint/project/.pipelinit.toml, cli/tests/fixtures/ruby/rubocop-lint/project/Gemfile, cli/tests/fixtures/ruby/rubocop-lint/project/Gemfile.lock, cli/tests/fixtures/ruby/rubocop-lint/project/README.md, cli/tests/fixtures/ruby/rubocop-lint/project/lib/main.rb, cli/tests/fixtures/ruby/rubocop-lint/project/main.gemspec, core/plugins/stack/mod.ts, core/plugins/stack/ruby/dependencies.ts, core/plugins/stack/ruby/linters.ts, core/plugins/stack/ruby/mod.ts, core/plugins/stack/ruby/rubocop.ts, core/plugins/stack/ruby/version.ts, core/templates/github/ruby/lint.yaml
Add ruby stack first implementation using rubocop as the default linter.
To test:
- Test in any project with the ruby stack
Example:
- https://github.com/joao10lima/test-ruby-pipelinit/runs/4139811124?check_suite_focus=true
Resolves: https://github.com/pipelinit/pipelinit-cli/issues/60
=> Add ruby stack first implementation

README.md, core/templates/github/java/sast.yaml, tests/fixtures/java/java-build-gradle/expected/.github/workflows/pipelinit.java.sast.yaml
Add a semgrep SAST (Static application security testing) stage for the Java stack, including the rulesets: "java"  (default ruleset for Java) and "security-audit" (scan code for potential security issues that require additional review).
Add pipelinit.java.sast.yaml file to expected folder.
Add SAST stage to Java stack on the Supported Stacks table in ReadMe File.
Resolves: #76 
To test:
In a GitHub repository with a java project, create a Pull Request of a branch. See the tests performed also in the Action tab.
=> feat: add java sast stage

README.md, core/templates/github/docker/sast.yaml, tests/fixtures/docker/docker-lint-build/expected/.github/workflows/pipelinit.docker.sast.yaml
Add a semgrep SAST (Static application security testing) stage for Docker.
Resolves: #75 
To test:
In a GitHub repository with a Docker file, create a Pull Request of a branch. See the tests performed also in the Action tab.
To test the semgrep generic.dockerfile.security.last-user-is-root.last-user-is-root  rule:
We get this on GitHub PR:
And this in GitHub Actions:
=> Feat: docker add sast stage

core/plugins/stack/python/version.ts, tests/default_test.ts, tests/fixtures/python/setup-flake8/expected/.github/workflows/pipelinit.python.format.yaml, tests/fixtures/python/setup-flake8/expected/.github/workflows/pipelinit.python.lint.yaml
Added support for setup.py, for discovering the Python version in the project.
#104 
Tested with the comand **pipelinit** in some Python projects:
- https://github.com/pipelinit/pipelinit-cli
- https://github.com/Madoshakalaka/pipenv-setup
- https://github.com/codrsquad/setupmeta
- https://github.com/aweidner/setupy
=> feat: add support for setup.py

.github/workflows/release.yaml, README.md, cli/Dockerfile, cli/README.md
Updates the Dockerfile definition to build the Pipelinit CLI Docker image without depending on a previous manual build step or any external artifacts besides the docker executable and the versioned source code.
That is, now the Docker build is independent and can run in an isolated CI job. This is required to make sure Pipelinit can generate pipelines to build itself.
The new image is slightly smaller too:
```
❯ docker image ls | grep pipelinit
pipelinit                                   latest         e7506bec06c9   7 seconds ago   114MB
ghcr.io/pipelinit/pipelinit-cli             latest         9215bc027a00   11 days ago     168MB
```
It's possible to shrink it further to 107MB, but at the cost of some complexity in the Dockerfile and build process:
<details>
<summary>Click to check the …
=> chore: improve Docker image build

core/plugins/stack/ruby/version.ts
- Fix the incorrect instruction (a Gemfile doesn't have a required_ruby_version attribute) 
- Add the missing one (Gemfile instructions).
- Suggest adding an extra line to improve the configuration if the project already has a Gemfile or .gemspec file
```
To fix this issue, consider one of the following suggestions:
1. Add the 'required_ruby_version' to your .gemspec file
The .gemspec file permits the specification of the adequate ruby version for this package.
See https://guides.rubygems.org/specification-reference/#required_ruby_version=
2. Add a version of Ruby to your Gemfile, using the ruby method
A Gemfile describes the gem dependencies required to execute associated Ruby code.
See https://bundler.io/man/gemfile.5.html#RUBY
3. Create a .ruby-version file
The .ruby-version file can …
```
=> fix: incomplete/incorrect remediation instructions

core/plugins/stack/python/packageManager.ts, tests/fixtures/python/python-pipenv/expected/.github/workflows/pipelinit.python.format.yaml, tests/fixtures/python/python-pipenv/expected/.github/workflows/pipelinit.python.lint.yaml, tests/fixtures/python/python-pipenv/expected/.github/workflows/pipelinit.python.test.yaml, tests/fixtures/python/python-pipenv/expected/.gitlab-ci/pipelinit.python.format.yaml, tests/fixtures/python/python-pipenv/expected/.gitlab-ci/pipelinit.python.lint.yaml, tests/fixtures/python/python-pipenv/expected/.gitlab-ci/pipelinit.python.sast.yaml, tests/fixtures/python/python-pipenv/expected/.gitlab-ci/pipelinit.python.test.yaml
This commit fixes the problem related to the issue:
https://github.com/pipelinit/pipelinit-cli/issues/133
By using the flag `--system` on the PipEnv installation
It does not create a '.venv' folder and install the dependencies
on direct on the default PIP path.
Resolves: https://github.com/pipelinit/pipelinit-cli/issues/133
Example:
- https://github.com/joao10lima/test-FAST/runs/4871867042?check_suite_focus=true
- https://github.com/joao10lima/test-FAST/runs/4871670250?check_suite_focus=true
=> fix: adjust pipenv install

core/plugins/stack/_shared/stylelint/mod.ts, core/plugins/stack/css/formatters.ts, core/plugins/stack/css/linters.ts, core/plugins/stack/docker/mod.ts, core/plugins/stack/helpers.ts, core/plugins/stack/html/formatters.ts, core/plugins/stack/html/linters.ts, core/plugins/stack/java/mod.ts, core/plugins/stack/javascript/formatters.ts, core/plugins/stack/javascript/linters.ts, core/plugins/stack/javascript/runtime.ts, core/plugins/stack/shell/mod.ts, core/plugins/stack/yaml/formatters.ts, core/types.ts
Adjusted stack implementations following the [code style guide](https://github.com/pipelinit/pipelinit-cli/blob/main/docs/reference/code-style-guide.md ) and best practices. 
Goals: 
- JavaScript runtime introspector
- Stylelint introspector
- Docker introspector
- Helper functions
Resolves: #147 
To test: run general tests
=> revise first stacks implementations #147

cli/Dockerfile
Fixed the docker image error. 
Resolves: #162 
```Dockerfile
ENTRYPOINT ["deno", "run", "--unstable", "--allow-read=.,/app/core/templates", "--allow-write=.", "/app/cli/pipelinit.ts"]
+CMD ["--"]
```
=> fix: docker image error
